//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.1 版自动生成。
// 
#pragma warning disable 1591

namespace OMS.Oms {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ObjectBaseOfOrderGoodsData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ObjectBaseOfOrderInfo))]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback HasOrderByTimeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = global::OMS.Properties.Settings.Default.OMS_Oms_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetOrderCompletedEventHandler GetOrderCompleted;
        
        /// <remarks/>
        public event HasOrderByTimeCompletedEventHandler HasOrderByTimeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OrderInfo[] GetOrder(string key, string ebayId, string sellId) {
            object[] results = this.Invoke("GetOrder", new object[] {
                        key,
                        ebayId,
                        sellId});
            return ((OrderInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetOrderAsync(string key, string ebayId, string sellId) {
            this.GetOrderAsync(key, ebayId, sellId, null);
        }
        
        /// <remarks/>
        public void GetOrderAsync(string key, string ebayId, string sellId, object userState) {
            if ((this.GetOrderOperationCompleted == null)) {
                this.GetOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrderOperationCompleted);
            }
            this.InvokeAsync("GetOrder", new object[] {
                        key,
                        ebayId,
                        sellId}, this.GetOrderOperationCompleted, userState);
        }
        
        private void OnGetOrderOperationCompleted(object arg) {
            if ((this.GetOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrderCompleted(this, new GetOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HasOrderByTime", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool HasOrderByTime(string key, string ebayId, string sellId, int hour) {
            object[] results = this.Invoke("HasOrderByTime", new object[] {
                        key,
                        ebayId,
                        sellId,
                        hour});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void HasOrderByTimeAsync(string key, string ebayId, string sellId, int hour) {
            this.HasOrderByTimeAsync(key, ebayId, sellId, hour, null);
        }
        
        /// <remarks/>
        public void HasOrderByTimeAsync(string key, string ebayId, string sellId, int hour, object userState) {
            if ((this.HasOrderByTimeOperationCompleted == null)) {
                this.HasOrderByTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHasOrderByTimeOperationCompleted);
            }
            this.InvokeAsync("HasOrderByTime", new object[] {
                        key,
                        ebayId,
                        sellId,
                        hour}, this.HasOrderByTimeOperationCompleted, userState);
        }
        
        private void OnHasOrderByTimeOperationCompleted(object arg) {
            if ((this.HasOrderByTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HasOrderByTimeCompleted(this, new HasOrderByTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderInfo : ObjectBaseOfOrderInfo {
        
        private string orderNoField;
        
        private string orderExNoField;
        
        private string txnIdField;
        
        private int payStatusField;
        
        private int isPrintField;
        
        private int orderStatusField;
        
        private double orderAmountField;
        
        private string orderCurrencyCodeField;
        
        private double orderSaleTaxField;
        
        private string payCurrencyCodeField;
        
        private double orderPayTaxField;
        
        private string transportModeField;
        
        private string sendPostCodeField;
        
        private string sendEmailField;
        
        private string sendPhoneField;
        
        private string sendAddressField;
        
        private string sendCountyField;
        
        private string sendCityField;
        
        private string sendStateField;
        
        private int addressIdField;
        
        private string sendCountryField;
        
        private string sendCountryCodeField;
        
        private string contactManField;
        
        private string payManField;
        
        private string payModeField;
        
        private string payEmailField;
        
        private string orderFormField;
        
        private string userNameFormField;
        
        private string orderNoteField;
        
        private System.DateTime addOrderTimeField;
        
        private System.DateTime payOrderTimeField;
        
        private System.DateTime sendOrderTImeField;
        
        private int enabledField;
        
        private int deletionStateCodeField;
        
        private int sortCodeField;
        
        private string descriptionField;
        
        private System.DateTime createOnField;
        
        private string createUserIdField;
        
        private string createByField;
        
        private string trackCodeField;
        
        private System.DateTime modifiedOnField;
        
        private string modifiedUserIdField;
        
        private string modifiedByField;
        
        private string companyIdField;
        
        private double sumAmountField;
        
        private OrderGoodsData[] goodsField;
        
        /// <remarks/>
        public string OrderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
            }
        }
        
        /// <remarks/>
        public string OrderExNo {
            get {
                return this.orderExNoField;
            }
            set {
                this.orderExNoField = value;
            }
        }
        
        /// <remarks/>
        public string TxnId {
            get {
                return this.txnIdField;
            }
            set {
                this.txnIdField = value;
            }
        }
        
        /// <remarks/>
        public int PayStatus {
            get {
                return this.payStatusField;
            }
            set {
                this.payStatusField = value;
            }
        }
        
        /// <remarks/>
        public int IsPrint {
            get {
                return this.isPrintField;
            }
            set {
                this.isPrintField = value;
            }
        }
        
        /// <remarks/>
        public int OrderStatus {
            get {
                return this.orderStatusField;
            }
            set {
                this.orderStatusField = value;
            }
        }
        
        /// <remarks/>
        public double OrderAmount {
            get {
                return this.orderAmountField;
            }
            set {
                this.orderAmountField = value;
            }
        }
        
        /// <remarks/>
        public string OrderCurrencyCode {
            get {
                return this.orderCurrencyCodeField;
            }
            set {
                this.orderCurrencyCodeField = value;
            }
        }
        
        /// <remarks/>
        public double OrderSaleTax {
            get {
                return this.orderSaleTaxField;
            }
            set {
                this.orderSaleTaxField = value;
            }
        }
        
        /// <remarks/>
        public string PayCurrencyCode {
            get {
                return this.payCurrencyCodeField;
            }
            set {
                this.payCurrencyCodeField = value;
            }
        }
        
        /// <remarks/>
        public double OrderPayTax {
            get {
                return this.orderPayTaxField;
            }
            set {
                this.orderPayTaxField = value;
            }
        }
        
        /// <remarks/>
        public string TransportMode {
            get {
                return this.transportModeField;
            }
            set {
                this.transportModeField = value;
            }
        }
        
        /// <remarks/>
        public string SendPostCode {
            get {
                return this.sendPostCodeField;
            }
            set {
                this.sendPostCodeField = value;
            }
        }
        
        /// <remarks/>
        public string SendEmail {
            get {
                return this.sendEmailField;
            }
            set {
                this.sendEmailField = value;
            }
        }
        
        /// <remarks/>
        public string SendPhone {
            get {
                return this.sendPhoneField;
            }
            set {
                this.sendPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string SendAddress {
            get {
                return this.sendAddressField;
            }
            set {
                this.sendAddressField = value;
            }
        }
        
        /// <remarks/>
        public string SendCounty {
            get {
                return this.sendCountyField;
            }
            set {
                this.sendCountyField = value;
            }
        }
        
        /// <remarks/>
        public string SendCity {
            get {
                return this.sendCityField;
            }
            set {
                this.sendCityField = value;
            }
        }
        
        /// <remarks/>
        public string SendState {
            get {
                return this.sendStateField;
            }
            set {
                this.sendStateField = value;
            }
        }
        
        /// <remarks/>
        public int AddressId {
            get {
                return this.addressIdField;
            }
            set {
                this.addressIdField = value;
            }
        }
        
        /// <remarks/>
        public string SendCountry {
            get {
                return this.sendCountryField;
            }
            set {
                this.sendCountryField = value;
            }
        }
        
        /// <remarks/>
        public string SendCountryCode {
            get {
                return this.sendCountryCodeField;
            }
            set {
                this.sendCountryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ContactMan {
            get {
                return this.contactManField;
            }
            set {
                this.contactManField = value;
            }
        }
        
        /// <remarks/>
        public string PayMan {
            get {
                return this.payManField;
            }
            set {
                this.payManField = value;
            }
        }
        
        /// <remarks/>
        public string PayMode {
            get {
                return this.payModeField;
            }
            set {
                this.payModeField = value;
            }
        }
        
        /// <remarks/>
        public string PayEmail {
            get {
                return this.payEmailField;
            }
            set {
                this.payEmailField = value;
            }
        }
        
        /// <remarks/>
        public string OrderForm {
            get {
                return this.orderFormField;
            }
            set {
                this.orderFormField = value;
            }
        }
        
        /// <remarks/>
        public string UserNameForm {
            get {
                return this.userNameFormField;
            }
            set {
                this.userNameFormField = value;
            }
        }
        
        /// <remarks/>
        public string OrderNote {
            get {
                return this.orderNoteField;
            }
            set {
                this.orderNoteField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime AddOrderTime {
            get {
                return this.addOrderTimeField;
            }
            set {
                this.addOrderTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime PayOrderTime {
            get {
                return this.payOrderTimeField;
            }
            set {
                this.payOrderTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SendOrderTIme {
            get {
                return this.sendOrderTImeField;
            }
            set {
                this.sendOrderTImeField = value;
            }
        }
        
        /// <remarks/>
        public int Enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }
        
        /// <remarks/>
        public int DeletionStateCode {
            get {
                return this.deletionStateCodeField;
            }
            set {
                this.deletionStateCodeField = value;
            }
        }
        
        /// <remarks/>
        public int SortCode {
            get {
                return this.sortCodeField;
            }
            set {
                this.sortCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreateOn {
            get {
                return this.createOnField;
            }
            set {
                this.createOnField = value;
            }
        }
        
        /// <remarks/>
        public string CreateUserId {
            get {
                return this.createUserIdField;
            }
            set {
                this.createUserIdField = value;
            }
        }
        
        /// <remarks/>
        public string CreateBy {
            get {
                return this.createByField;
            }
            set {
                this.createByField = value;
            }
        }
        
        /// <remarks/>
        public string TrackCode {
            get {
                return this.trackCodeField;
            }
            set {
                this.trackCodeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ModifiedOn {
            get {
                return this.modifiedOnField;
            }
            set {
                this.modifiedOnField = value;
            }
        }
        
        /// <remarks/>
        public string ModifiedUserId {
            get {
                return this.modifiedUserIdField;
            }
            set {
                this.modifiedUserIdField = value;
            }
        }
        
        /// <remarks/>
        public string ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyId {
            get {
                return this.companyIdField;
            }
            set {
                this.companyIdField = value;
            }
        }
        
        /// <remarks/>
        public double SumAmount {
            get {
                return this.sumAmountField;
            }
            set {
                this.sumAmountField = value;
            }
        }
        
        /// <remarks/>
        public OrderGoodsData[] Goods {
            get {
                return this.goodsField;
            }
            set {
                this.goodsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderGoodsData : ObjectBaseOfOrderGoodsData {
        
        private string orderNameField;
        
        private string itemIdField;
        
        private string itemNameField;
        
        private string itemNoField;
        
        private double itemPriceField;
        
        private string itemImgField;
        
        private int itemNumField;
        
        private string itemAttrField;
        
        private int enabledField;
        
        private int deletionStateCodeField;
        
        private int sortCodeField;
        
        private string descriptionField;
        
        private System.DateTime createOnField;
        
        private string createUserIdField;
        
        private string createByField;
        
        private System.DateTime modifiedOnField;
        
        private string modifiedUserIdField;
        
        private string modifiedByField;
        
        private string companyIdField;
        
        /// <remarks/>
        public string OrderName {
            get {
                return this.orderNameField;
            }
            set {
                this.orderNameField = value;
            }
        }
        
        /// <remarks/>
        public string ItemId {
            get {
                return this.itemIdField;
            }
            set {
                this.itemIdField = value;
            }
        }
        
        /// <remarks/>
        public string ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
            }
        }
        
        /// <remarks/>
        public string ItemNo {
            get {
                return this.itemNoField;
            }
            set {
                this.itemNoField = value;
            }
        }
        
        /// <remarks/>
        public double ItemPrice {
            get {
                return this.itemPriceField;
            }
            set {
                this.itemPriceField = value;
            }
        }
        
        /// <remarks/>
        public string ItemImg {
            get {
                return this.itemImgField;
            }
            set {
                this.itemImgField = value;
            }
        }
        
        /// <remarks/>
        public int ItemNum {
            get {
                return this.itemNumField;
            }
            set {
                this.itemNumField = value;
            }
        }
        
        /// <remarks/>
        public string ItemAttr {
            get {
                return this.itemAttrField;
            }
            set {
                this.itemAttrField = value;
            }
        }
        
        /// <remarks/>
        public int Enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }
        
        /// <remarks/>
        public int DeletionStateCode {
            get {
                return this.deletionStateCodeField;
            }
            set {
                this.deletionStateCodeField = value;
            }
        }
        
        /// <remarks/>
        public int SortCode {
            get {
                return this.sortCodeField;
            }
            set {
                this.sortCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreateOn {
            get {
                return this.createOnField;
            }
            set {
                this.createOnField = value;
            }
        }
        
        /// <remarks/>
        public string CreateUserId {
            get {
                return this.createUserIdField;
            }
            set {
                this.createUserIdField = value;
            }
        }
        
        /// <remarks/>
        public string CreateBy {
            get {
                return this.createByField;
            }
            set {
                this.createByField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ModifiedOn {
            get {
                return this.modifiedOnField;
            }
            set {
                this.modifiedOnField = value;
            }
        }
        
        /// <remarks/>
        public string ModifiedUserId {
            get {
                return this.modifiedUserIdField;
            }
            set {
                this.modifiedUserIdField = value;
            }
        }
        
        /// <remarks/>
        public string ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyId {
            get {
                return this.companyIdField;
            }
            set {
                this.companyIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderGoodsData))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjectBaseOfOrderGoodsData {
        
        private int idField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjectBaseOfOrderInfo {
        
        private int idField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetOrderCompletedEventHandler(object sender, GetOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OrderInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrderInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void HasOrderByTimeCompletedEventHandler(object sender, HasOrderByTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasOrderByTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HasOrderByTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591